name: Super-Linter

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
          
      - name: create string
        run: |
          MY_STRING=["https://test2.html","https://test1.html","https://test.html"]
          echo "::set-output name=content::$MY_STRING"
        id: my_string
        
      - name: display string
        run: |
          echo "The string is: join(${{ steps.my_string.outputs.content }}, ', ')"
